## 1. Creating 1-D list

In [4]:
import numpy as np

### Python

In [5]:
myList = [index for index in range(10)]
myList

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

### NumPy

In [6]:
myList2 = np.arange(10)
myList2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## 2. Creating 2-D list

### Python

In [7]:
myList1 = [[i * j for i in range(3)] for j in range(3)]
myList1

[[0, 0, 0], [0, 1, 2], [0, 2, 4]]

### NumPy

In [13]:
myList2 = np.arange(9).reshape(3,3)
myList2

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

## 3. Stacking two arrays vertically

In [25]:
## repeat(numberToBeRepeated, size)
b = np.repeat(1, 10)
print(b)

[1 1 1 1 1 1 1 1 1 1]


## 4. Stacking two arrays vertically

In [19]:
a = np.arange(10).reshape(2,-1)
print(a)
b = np.repeat(1, 10).reshape(2,-1)
print(b)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[1 1 1 1 1]
 [1 1 1 1 1]]


In [23]:
##axis = 0 means add rows of a and b
np.concatenate([a, b], axis=0)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

## 5. Stacking two arrays horizontally

In [24]:
##axis = 1 means add columns of a and b
np.concatenate([a, b], axis=1)

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

## 6. NumPy Tile

In [26]:
## tile(arrayToBeTiled, numberOfTimes)
np.tile([1,2,3], 4)

array([1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

## 7. Get common items in two arrays

In [27]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.intersect1d(a,b)

array([2, 4])

## 8. Remove common element of an array

In [28]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
np.setdiff1d(a,b)

array([1, 2, 3, 4])

## 9. NumPy where

In [30]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.where(a==b)

(array([1, 3, 5, 7]),)

## 10. Load data from a text file

In [ ]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])

## 11. NumPy Mean

In [ ]:
mean = np.mean(sepallength)

## 12. NumPy Median

In [ ]:
median = np.median(sepallength)

## 13. NumPy Standard Deviation

In [ ]:
standardDeviation = np.std(sepallength)

## 14. NumPy Max

In [34]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
a.max()

6

## 15. NumPy Min

In [35]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
a.min()

1

## 16. NumPy Percentile

In [37]:
#Calculate q-th percentile
a = np.array([[10, 7, 4], [3, 2, 1]])
np.percentile(a, 50)

3.5

## 17. NumPy Search for null in array

In [38]:
np.isnan(np.nan)

True

## 18. NumPy Unique

In [39]:
np.unique([1, 1, 2, 2, 3, 3])

array([1, 2, 3])

## 19. NumPy Digitize

In [40]:
#numpy.digitize(x, bins, right=False)
x = np.array([0.2, 6.4, 3.0, 1.6])
bins = np.array([0.0, 1.0, 2.5, 4.0, 10.0])
inds = np.digitize(x, bins)
inds

array([1, 4, 3, 2])

## 20. NumPy Sort

In [41]:
a = np.array([[1,4],[3,1]])
np.sort(a)                # sort along the last axis

array([[1, 4],
       [1, 3]])

## 21. NumPy Argmax

In [43]:
#numpy.argmax(a, axis=None, out=None)
#Returns the indices of the maximum values along an axis.
a = np.arange(6).reshape(2,3) + 10
np.argmax(a)

5

## 22. NumPy Clip

In [44]:
#numpy.clip(a, a_min, a_max, out=None, **kwargs)
#Clip (limit) the values in an array.
a = np.arange(10)
np.clip(a, 1, 8)

array([1, 1, 2, 3, 4, 5, 6, 7, 8, 8])

## 23. NumPy ArgSort

In [45]:
#Returns the indices that would sort an array.
x = np.array([3, 1, 2])
x

array([3, 1, 2])

In [46]:
np.argsort(x)

array([1, 2, 0])

## 24. NumPy ArgPartition

In [47]:
x = np.array([3, 4, 2, 1])
x[np.argpartition(x, 3)]

array([2, 1, 3, 4])

## 25. NumPy Flat

In [49]:
x = np.arange(1, 7).reshape(2, 3)
x

array([[1, 2, 3],
       [4, 5, 6]])

In [50]:
x.flat[3]

4

## 26. NumPy Ravel

In [51]:
x = np.array([[1, 2, 3], [4, 5, 6]])
x

array([[1, 2, 3],
       [4, 5, 6]])

In [52]:
np.ravel(x)

array([1, 2, 3, 4, 5, 6])

## 27. NumPy Flatten

In [53]:
a = np.array([[1,2], [3,4]])
a

array([[1, 2],
       [3, 4]])

In [54]:
#Return a copy of the array collapsed into one dimension.
a.flatten()

array([1, 2, 3, 4])

## 28. NumPy MoveAxis

In [58]:
x = np.zeros((3, 4, 5))
x

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [59]:
x.shape

(3, 4, 5)

In [60]:
#Move axes of an array to new positions.
np.moveaxis(x, 0, -1)

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [61]:
x.shape

(3, 4, 5)

## 29. NumPy SwapAxes

In [62]:
x = np.array([[1,2,3]])
x

array([[1, 2, 3]])

In [63]:
#numpy.swapaxes(a, axis1, axis2)
#Interchange two axes of an array.
np.swapaxes(x,0,1)

array([[1],
       [2],
       [3]])

## 30. NumPy Transpose

In [64]:
x = np.arange(4).reshape((2,2))
x

array([[0, 1],
       [2, 3]])

In [65]:
np.transpose(x)

array([[0, 2],
       [1, 3]])

## 31. NumPy Split

In [66]:
x = np.arange(9.0)
x

array([0., 1., 2., 3., 4., 5., 6., 7., 8.])

In [67]:
#numpy.split(ary, indices_or_sections, axis=0)
#Split an array into multiple sub-arrays as views into array.
np.split(x, 3)

[array([0., 1., 2.]), array([3., 4., 5.]), array([6., 7., 8.])]

## 32. NumPy Dsplit

In [69]:
x = np.arange(16.0).reshape(2, 2, 4)
x

array([[[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.]],

       [[ 8.,  9., 10., 11.],
        [12., 13., 14., 15.]]])

In [70]:
#numpy.dsplit(ary, indices_or_sections)
#Split array into multiple sub-arrays along the 3rd axis (depth).
np.dsplit(x, 2)

[array([[[ 0.,  1.],
         [ 4.,  5.]],
 
        [[ 8.,  9.],
         [12., 13.]]]),
 array([[[ 2.,  3.],
         [ 6.,  7.]],
 
        [[10., 11.],
         [14., 15.]]])]

## 33. NumPy Hsplit

In [71]:
x = np.arange(16.0).reshape(4, 4)
x

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.],
       [12., 13., 14., 15.]])

In [72]:
np.hsplit(x, 2)

[array([[ 0.,  1.],
        [ 4.,  5.],
        [ 8.,  9.],
        [12., 13.]]),
 array([[ 2.,  3.],
        [ 6.,  7.],
        [10., 11.],
        [14., 15.]])]

## 34. NumPy Vsplit

In [73]:
x = np.arange(16.0).reshape(4, 4)
x

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.],
       [12., 13., 14., 15.]])

In [74]:
np.vsplit(x, 2)

[array([[0., 1., 2., 3.],
        [4., 5., 6., 7.]]),
 array([[ 8.,  9., 10., 11.],
        [12., 13., 14., 15.]])]

## 35. NumPy Delete

In [75]:
arr = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [76]:
#numpy.delete(arr, obj, axis=None)
#Return a new array with sub-arrays along an axis deleted. For a one dimensional array, this returns those entries not returned by arr[obj].
np.delete(arr, 1, 0)

array([[ 1,  2,  3,  4],
       [ 9, 10, 11, 12]])

## 36. NumPy Insert

In [77]:
a = np.array([[1, 1], [2, 2], [3, 3]])
a

array([[1, 1],
       [2, 2],
       [3, 3]])

In [78]:
np.insert(a, 1, 5)

array([1, 5, 1, 2, 2, 3, 3])

## 37. NumPy Trim Zeroes

In [79]:
a = np.array((0, 0, 0, 1, 2, 3, 0, 2, 1, 0))
a

array([0, 0, 0, 1, 2, 3, 0, 2, 1, 0])

In [80]:
#Trim the leading and/or trailing zeros from a 1-D array or sequence.
np.trim_zeros(a)

array([1, 2, 3, 0, 2, 1])

## 38. NumPy Flip

In [81]:
a = np.arange(8).reshape((2,2,2))
a

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [82]:
#Reverse the order of elements in an array along the given axis.
np.flip(a, 0)

array([[[4, 5],
        [6, 7]],

       [[0, 1],
        [2, 3]]])

## 39. NumPy Diag

In [83]:
x = np.arange(9).reshape((3,3))
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [84]:
#Extract a diagonal or construct a diagonal array.
np.diag(x)

array([0, 4, 8])

## 40. NumPy FlipLr

In [85]:
A = np.diag([1.,2.,3.])
A

array([[1., 0., 0.],
       [0., 2., 0.],
       [0., 0., 3.]])

In [86]:
np.fliplr(A)

array([[0., 0., 1.],
       [0., 2., 0.],
       [3., 0., 0.]])

## 41. NumPy FlipUd

In [87]:
A = np.diag([1.0, 2, 3])
A

array([[1., 0., 0.],
       [0., 2., 0.],
       [0., 0., 3.]])

In [88]:
#Flip array in the up/down direction.
np.flipud(A)

array([[0., 0., 3.],
       [0., 2., 0.],
       [1., 0., 0.]])

## 42. NumPy Roll

In [89]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [90]:
#numpy.roll(a, shift, axis=None)
#Roll array elements along a given axis.
np.roll(x, 2)

array([8, 9, 0, 1, 2, 3, 4, 5, 6, 7])

## 43. NumPy Rot90

In [91]:
m = np.array([[1,2],[3,4]], int)
m

array([[1, 2],
       [3, 4]])

In [93]:
#Rotate an array by 90 degrees in the plane specified by axes.
np.rot90(m)

array([[2, 4],
       [1, 3]])

## 44. NumPy Binary_Repr

In [95]:
#Return the binary representation of the input number as a string.
np.binary_repr(3)

'11'

## 45. NumPy Bitwise_And

In [96]:
np.binary_repr(13)

'1101'

In [97]:
np.binary_repr(17)

'10001'

In [99]:
np.bitwise_and(13, 17)
#The number 13 is represented by 00001101. Likewise, 17 is represented by 00010001. The bit-wise AND of 13 and 17 is therefore 000000001, or 1:

1

## 46. NumPy Bitwise_Or

In [100]:
np.bitwise_or(13, 16)
np.binary_repr(29)

'11101'

## 47. NumPy Bitwise_Xor

In [101]:
np.bitwise_xor(13, 17)

28

In [102]:
np.binary_repr(28)

'11100'

## 48. NumPy Invert

In [104]:
#Compute bit-wise inversion, or bit-wise NOT, element-wise.
x = np.invert(np.array(13, dtype=np.uint8))
x

242

## 49. NumPy Left_Shift

In [105]:
np.binary_repr(5)

'101'

In [107]:
#Shift the bits of an integer to the left.
np.binary_repr(np.left_shift(5, 2))

'10100'

## 50. NumPy Right_Shift

In [108]:
np.binary_repr(10)

'1010'

In [109]:
np.binary_repr(np.right_shift(10, 1))

'101'